export const SYSTEM_EVENT_TYPE = {
  ENGINE_STATE_INVALID: 'ENGINE_STATE_INVALID',
  ENGINE_LOOP_DELAYED: 'ENGINE_LOOP_DELAYED',
  WS_BACKPRESSURE: 'WS_BACKPRESSURE',
  WS_CLIENT_DROPPED: 'WS_CLIENT_DROPPED',
  WS_SERIALIZE_FAILED: 'WS_SERIALIZE_FAILED',
  EXCHANGE_API_ERROR: 'EXCHANGE_API_ERROR',
  EXCHANGE_TIMEOUT: 'EXCHANGE_TIMEOUT',
  EXCHANGE_RETRY_EXHAUSTED: 'EXCHANGE_RETRY_EXHAUSTED',
  SUPABASE_TIMEOUT: 'SUPABASE_TIMEOUT',
  SUPABASE_WRITE_RETRY: 'SUPABASE_WRITE_RETRY',
  SUPABASE_WRITE_FAILED: 'SUPABASE_WRITE_FAILED',
  EVENT_OUT_OF_ORDER: 'EVENT_OUT_OF_ORDER',
  EVENT_DUPLICATED: 'EVENT_DUPLICATED',
  CIRCUIT_OPENED: 'CIRCUIT_OPENED',
  CIRCUIT_HALF_OPEN: 'CIRCUIT_HALF_OPEN',
  CIRCUIT_CLOSED: 'CIRCUIT_CLOSED',
  DB_WRITE_FAILED: 'DB_WRITE_FAILED',
  QUEUE_PUBLISH_FAILED: 'QUEUE_PUBLISH_FAILED',
  KILL_SWITCH_TRIGGERED: 'KILL_SWITCH_TRIGGERED',
  RISK_LIMIT_BREACH: 'RISK_LIMIT_BREACH',
  LIVE_GUARD_BLOCKED: 'LIVE_GUARD_BLOCKED'
} as const;

export type SystemEventType =
  (typeof SYSTEM_EVENT_TYPE)[keyof typeof SYSTEM_EVENT_TYPE];

export const SYSTEM_EVENT_LEVEL = {
  DEBUG: 'DEBUG',
  INFO: 'INFO',
  WARN: 'WARN',
  ERROR: 'ERROR',
  FATAL: 'FATAL'
} as const;

export type SystemEventLevel =
  (typeof SYSTEM_EVENT_LEVEL)[keyof typeof SYSTEM_EVENT_LEVEL];
